### ISSUE TITLE
1.17 / 1.18 snapshots version?

### ISSUE THREAD

**Issue by K0-RR** [MadAlchemist/Zombienation#1]

**Comment by MadAlchemist** [comment]
1.17 is planned, but currently is not possible because I have cooked my video card that supported required opengl version. Now I am stuck to integrated video and 1.16 for a while, because these damn things are expensive. There was no plans for 1.18 initially because porting to 1.17 is already pain in ass, but, who knows? Maybe I will do this too. But only when I will replace broken video card, run out of new content ideas, port to 1.17 and maybe fabric... Then, MAYBE, i will try to port it to 1.18 or whatever will be latest at that moment.
